default:
  # general options
  UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36
  OutputDir: datasets/bing
  FetchesPerDelay: 5
  FetchDelay: .5

  # Demagog scraping options
  UseExistingStatements: true
  DemagogFromPage: 1
  DemagogToPage: 1
  IncludeExplanation: true
  IncludeAuthor: true
  IncludeAssessment: false
  IncludeDate: true
  StmtStartIndex: 1

  # Grouding context options
  ScrapeWithContext: true
  ContextLinkOnly: false
  ContextLLM: none
  ContextNum: 10
  ContextNumBuffer: 15
  SearchDelay: 1
  SearchesPerDelay: 3
  SearchAPI: bing
  BingAPIKey: $BING_API_KEY

criteria:
  # general options
  UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.
  OutputDir: datasets/criteria
  FetchesPerDelay: 1
  FetchDelay: 1

  # Demagog scraping options
  UseExistingStatements: true
  DemagogFromPage: 1
  DemagogToPage: 1
  IncludeExplanation: true
  IncludeAuthor: true
  IncludeAssessment: false
  IncludeDate: true
  StmtStartIndex: 1

  # Grouding context options
  ScrapeWithContext: true
  ContextLinkOnly: false
  ContextLLM: none
  ContextNum: 10
  ContextNumBuffer: 15
  SearchDelay: 1
  SearchesPerDelay: 1
  SearchAPI: criteria
  BingAPIKey: $BING_API_KEY
