default:
  # general options
  UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36
  OutputDir: dataset
  FetchesPerDelay: 10
  FetchDelay: .5
  OverwriteOutput: False

  # Demagog scraping options
  DemagogFromPage: 1
  DemagogToPage: 500
  IncludeExplanation: true
  IncludeAuthor: true
  IncludeAssessment: false
  IncludeDate: true
  IncludeContext: true
  OnlyWithAssesment:

  # Grouding context options
  ContextLinkOnly: false
  ContextLLM: none
  ContextNum: 0
  ContextNumBuffer: 0
  SearchDelay: 1
  SearchesPerDelay: 3
  SearchAPI: bing
  GoogleAPIKey: AIzaSyDEwtqmI5xiRWQxvFVCzBrRfKA5zIKkxZU
  BingAPIKey: d7baa2059c9643f7a660e2c409456c84

