default:
  NOI: True
  RPM: 600
  APIKey: $TOGETHER_API_KEY
  APIBaseURL: https://api.together.xyz/v1
  StatementsPath: "../datasets/samples/statements_after_9_2024_sample.json"
  UseRephrased: False
  ResultsFolder: "results/after_9_2024"
  RephrasingModel: meta-llama/Llama-3.3-70B-Instruct-Turbo

  ModelName: 
    - llama-3.3-70b-it
    - qwen-2.5-it
    - mixtral-8x22b-i
    - gemma-2-27b-it
    - llama-3.1-405b-it
    - llama-3.1-8b-it
  ModelAPINames: 
    - meta-llama/Llama-3.3-70B-Instruct-Turbo
    - Qwen/Qwen2.5-72B-Instruct-Turbo
    - mistralai/Mixtral-8x22B-Instruct-v0.1
    - google/gemma-2-27b-it
    - meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo
    - meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo

