default:
  # general options
  UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36
  OutputDir: datasets/with_evidence/bing
  FetchesPerDelay: 15
  FetchDelay: .5

  # Demagog scraping options
  UseExistingStatements: true
  YearListPath: datasets/years
  DemagogFromPage: -1
  DemagogToPage: null
  FromYear: -1
  ToYear: -1
  StmtStartIndex: 1

  # Evidence retrieval options
  ScrapeWithEvidence: true
  EvidenceLinkOnly: false
  EvidenceLLM: none
  EvidenceNum: 10
  EvidenceNumBuffer: 15
  SearchDelay: 1
  SearchesPerDelay: 3
  SearchAPI: bing
  BingAPIKey: $BING_API_KEY
